## Numpy packages

1. numerical data
2. computations


In [7]:
import numpy as np

### Difference Between numpy array and list:
1. less memory
2. fast
3. convenient

In [8]:
#1- dimensional array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a1.ndim

2

In [15]:
a1.shape

(3, 3)

In [12]:
a2 = np.array

In [20]:
a3=np.array([])
        

In [21]:
a3=np.append(a3,int(input()))
a3

2


array([2.])

In [22]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([ 2., 23., 34., 45., 56., 67.])

## slicing

In [16]:
print(a3[3])

NameError: name 'a3' is not defined

In [17]:
print(a2[1,1])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
print(a2[2:,:])

TypeError: 'builtin_function_or_method' object is not subscriptable

## indexing with boolean array

In [23]:
arr1 = np.arange(1,21).reshape(5,4)
arra1

NameError: name 'arra1' is not defined

In [24]:
result = (arr1 %2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [26]:

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
print()

## Attributes:
1. size
2. item size
3. dtype
4. ndim
5. shape

In [27]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


## Functions:
1. zeros
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [29]:
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
o = np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
f = np.full((2,2),"swathi")
print(f)

[['swathi' 'swathi']
 ['swathi' 'swathi']]


In [33]:
#eye()
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
#linspace() -->linear spacing elements
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
a = np.arange(1,13,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [40]:
#ravel()
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


## functions:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [41]:
print(a.min())
print(a.max())

1
11


In [45]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

36


AxisError: axis 1 is out of bounds for array of dimension 1

In [46]:
np.sqrt(a)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479])

In [47]:
np.mean(a)

6.0

In [48]:
np.median(a)

6.0

In [49]:
np.std(a)

3.415650255319866

## Mathematical Operations: +,-,*,/,%


## Applying user-defined function:


In [52]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [53]:
#1/(1+1) --> x/(x+1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [55]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [56]:
help(np.linalag)

AttributeError: module 'numpy' has no attribute 'nilag'