In [3]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

62
0.7401558572877139


In [4]:
#creating  n-dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[42 93 10]
[[25 44  3 35]
 [25  7 28 72]
 [ 2 78 46 19]]
[[[84 21]
  [21 63]
  [75 77]
  [84 99]]

 [[35  4]
  [89 85]
  [30 64]
  [44 53]]

 [[60 20]
  [ 7 85]
  [65 80]
  [ 5 19]]]


In [5]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.5590949695277756
[0.44001751 0.06197316 0.14760736]
[[0.44190706 0.46378894 0.4505215 ]
 [0.0996794  0.95732435 0.33848785]]


In [9]:
a = random.randint(100,size=(3,2)).ravel()
a

array([63, 40, 74, 70, 31, 99])

In [10]:
random.choice(a)

31

In [11]:
random.choice([1,2,3,4,5],size=(4,4))

array([[1, 5, 4, 3],
       [5, 3, 5, 2],
       [4, 3, 4, 2],
       [4, 5, 5, 3]])

### pandas:
1. Data manipulation,analysis and cleaning
2. Tabular data,Unlable data


### Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary -->DataFrame

In [9]:
import pandas as pd
import numpy as np
dic1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dic2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dic1,"second":dic2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [10]:
#simple dictionary -->DataFrame
d1 = {"name":["preethi","swathi","swetha"],"address":["hyd","sircilla","TS"],"ph no":["9553923118","22222","84758247"]}
df1 = pd.DataFrame(d1)
df1

name   address       ph no
0  preethi       hyd  9553923118
1   swathi  sircilla       22222
2   swetha        TS    84758247

In [11]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,34.45,45.5,56.4,76.5,78.45,80.2,83.4,90.4])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.50       d
4        5    56.40       e
5        6    76.50       f
6        7    78.45       g
7        8    80.20       h
8        9    83.40       i
9       10    90.40       j

### Selecting the data from the DataFrame:
1. loc
2. iloc

In [12]:
df3["column2"]

0    12.23
1    23.34
2    34.45
3    45.50
4    56.40
5    76.50
6    78.45
7    80.20
8    83.40
9    90.40
Name: column2, dtype: float64

In [13]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    34.45       c
3    45.50       d
4    56.40       e
5    76.50       f
6    78.45       g
7    80.20       h
8    83.40       i
9    90.40       j

In [14]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [15]:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    34.45
3        4    45.50
4        5    56.40
5        6    76.50

In [16]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [17]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [18]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [19]:
df3.shape

(10, 3)

In [20]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [21]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [22]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.50       d
4        5    56.40       e

In [23]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c

In [24]:
df3.tail()

column1  column2 column3
5        6    76.50       f
6        7    78.45       g
7        8    80.20       h
8        9    83.40       i
9       10    90.40       j

In [25]:
df3.tail(4)


column1  column2 column3
6        7    78.45       g
7        8    80.20       h
8        9    83.40       i
9       10    90.40       j

In [26]:
#Selects random data
df3.sample()

column1  column2 column3
5        6     76.5       f

In [27]:
df3.sample(6)

column1  column2 column3
2        3    34.45       c
3        4    45.50       d
9       10    90.40       j
1        2    23.34       b
6        7    78.45       g
5        6    76.50       f

In [28]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  58.087000
std     3.02765  27.804392
min     1.00000  12.230000
25%     3.25000  37.212500
50%     5.50000  66.450000
75%     7.75000  79.762500
max    10.00000  90.400000

In [29]:
#Renaming the column headers
df3 = df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   34.45     c
3      4   45.50     d
4      5   56.40     e
5      6   76.50     f
6      7   78.45     g
7      8   80.20     h
8      9   83.40     i
9     10   90.40     j